//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XPPlayer.rc
//
#define IDD_PP_ABOUT                    107
#define IDR_MAINFRAME                   128
#define IDR_SHORTCUTKEY                 128
#define IDR_MENU                        138
#define IDD_DIALOG_FILTERSPROP          139
#define IDD_DIALOG_PLAYLIST             140
#define IDR_MENU_PLS                    141
#define IDD_DIALOG_OPTIONS              144
#define IDD_PP_SUBTITLES                145
#define IDD_PP_FILETYPES                146
#define IDD_PP_SETUP                    147
#define IDD_PP_OPTIONS                  148
#define IDR_MENU1                       148
#define IDR_MENU_CALLBACK               148
#define IDD_PP_PLAY                     149
#define IDI_ICON_MOVIE01                149
#define IDD_PP_STARTUP                  150
#define IDI_ICON_MOVIE02                150
#define IDD_PP_TIMECORRECTION           151
#define IDD_PP_SUBTITLES_TIME           151
#define IDI_ICON_MOVIE03                151
#define IDD_PP_SKINBROWSER              152
#define IDI_ICON_MOVIE04                152
#define IDD_PP_SUBTITLES_GENERAL        153
#define IDI_ICON_MOVIE05                153
#define IDB_BITMAP_PATTERN              159
#define IDR_AUTHOR                      161
#define IDR_ABOUT                       162
#define IDR_ABOUTSCROLLER               163
#define IDR_ABOUTWWW                    167
#define IDR_ABOUTMAIL                   168
#define IDR_ABOUTREGISTERIT             169
#define IDR_SETUP                       170
#define IDD_DIALOG_TIMEOUT              171
#define IDR_DEFAULTSKIN                 172
#define IDC_LIST_FILTERS                1001
#define IDC_BUTTON_PROP                 1002
#define IDC_LIST_PLAYLIST               1003
#define IDC_BUTTON_DEF                  1003
#define IDC_BUTTON1                     1004
#define IDC_BUTTON_CLOSE                1004
#define IDC_BUTTON_SELECTSKIN           1004
#define IDC_BUTTON_CHANGEFONT           1004
#define IDC_BUTTON_ALL                  1004
#define IDC_BUTTON_REGISTER             1004
#define IDAPPLY                         1005
#define IDC_BUTTON2                     1005
#define IDC_BUTTON_SAVEAS               1005
#define IDC_BUTTON_THEIMP               1005
#define IDC_BUTTON3                     1006
#define IDC_SLIDER_BRIGHTNESS           1012
#define IDC_SLIDER_CONTRAST             1013
#define IDC_SLIDER_SATURATION           1014
#define IDC_STATIC_BRIGHTNESS           1015
#define IDC_STATIC_CONTRAST             1016
#define IDC_STATIC_SATURATION           1017
#define IDC_TREE_PAGE                   1018
#define IDC_SBLIST_SKINS                1024
#define IDC_STATIC_PREVNOTAVAIL         1025
#define IDC_TEXT_PREVNOTAVAIL           1025
#define IDC_STATIC_COMMENT              1026
#define IDC_TEXTT_COMMENT               1026
#define IDC_STATIC_COMMENTTEXT          1027
#define IDC_TEXT_COMMENT                1027
#define IDC_STATIC_AUTHOR               1028
#define IDC_TEXTT_AUTHOR                1028
#define IDC_STATIC_AUTHORTEXT           1029
#define IDC_TEXT_AUTHOR                 1029
#define IDC_STATIC_NAME                 1030
#define IDC_TEXTT_NAME                  1030
#define IDC_STATIC_NAMETEXT             1031
#define IDC_TEXT_NAME                   1031
#define IDC_STATIC_VERSION              1032
#define IDC_TEXTT_VERSION               1032
#define IDC_STATIC_VERSIONTEXT          1033
#define IDC_TEXT_VERSION                1033
#define IDC_COMBO_MODESEL               1034
#define IDC_COMBO_MODESEL2              1035
#define IDC_COMBO_MROWDIR               1035
#define IDC_COMBO_OUTLINESEL            1036
#define IDC_SPIN1                       1038
#define IDC_SPIN_TEXTROWS               1038
#define IDC_SPIN_REWINDBY               1038
#define IDC_SPIN2                       1039
#define IDC_SPIN_DISTANCE               1039
#define IDC_SPIN_MAXPLSFILES            1039
#define IDC_SPIN3                       1040
#define IDC_SPIN_TIMETOHIDE             1041
#define IDC_EDIT1                       1042
#define IDC_EDIT_TEXTROWS               1042
#define IDC_EDIT_HIDEAFTER              1042
#define IDC_EDIT2                       1043
#define IDC_EDIT_DISTANCE               1043
#define IDC_EDIT_REWINDBY               1043
#define IDC_EDIT3                       1044
#define IDC_EDIT_TIMETOHIDE             1045
#define IDC_CHECK_SHORTBKGRND           1048
#define IDC_CHECK_RGNPRECISE            1049
#define IDC_CHECK3                      1050
#define IDC_CHECK_AUTOSIZE              1050
#define IDC_CHECK_ALWAYSONTOP           1050
#define IDC_CHECK_TRANSPARENTBKGRND     1051
#define IDC_TEXT_FONTCOL                1052
#define IDC_TEXT_OUTLINECOL             1055
#define IDC_TEXT_BKGRNDCOL              1056
#define IDC_TEXTT_MODESEL               1057
#define IDC_TEXTT_OUTLINESEL            1058
#define IDC_BUTTON_DEFAULT              1059
#define IDC_BUTTON_APPLY                1060
#define IDC_TEXTT_TITLE                 1061
#define IDD_TEXTT_TIMETOHIDE            1062
#define IDC_SCROLLBAR_POSITION          1063
#define IDD_TEXTT2_TIMETOHIDE           1064
#define IDD_TEXTT2_ROWDISTANCE          1065
#define IDD_TEXTT_ROWDISTANCE           1066
#define IDD_TEXTT_TITLETIMEPROP         1067
#define IDD_TEXTT_TEXTROWS              1068
#define IDD_TEXTT_MROWDIR               1069
#define IDD_TEXTT_TITLEPOS              1070
#define IDC_DATETIMEPICKER1             1071
#define IDC_DATETIME_TIME               1071
#define IDC_RADIO1                      1072
#define IDC_RADIO_DELAY                 1072
#define IDC_RADIO2                      1073
#define IDC_RADIO_SPEEDUP               1073
#define IDC_CHECK1                      1074
#define IDC_CHECK_OFFSET                1074
#define IDC_CHECK_MAXOVERTASK           1075
#define IDC_CHECK6                      1079
#define IDC_CHECK_AUTOPLAY              1079
#define IDC_COMBO1                      1080
#define IDC_COMBO_CURRLANG              1080
#define IDC_LIST1                       1081
#define IDC_COMBO_OPENNOMOVIE           1081
#define IDC_LIST_EXTENSIONS             1081
#define IDC_CHECK4                      1083
#define IDC_CHECK_AUTOREWIND            1083
#define IDC_CHECK5                      1084
#define IDC_CHECK_LOOP                  1084
#define IDC_COMBO_OPENWITHMOVIE         1085
#define IDC_TEXTT_OPENONMOVIE           1086
#define IDC_TEXTT2_OPENONMOVIE          1087
#define IDC_TEXTT_OPENWITHMOVIE         1088
#define IDC_TEXTT2_OPENWITHMOVIE        1089
#define IDC_TEXTT_TITLEGENERAL          1090
#define IDC_TEXTT_TITLEPLAYLIST         1091
#define IDC_CHECK_HIDEWHENFS            1092
#define IDC_TEXTT_HIDEAFTER             1093
#define IDC_TEXTT2_HIDEAFTER            1094
#define IDC_TEXTT_MAXPLSFILES           1095
#define IDC_EDIT_MAXPLSFILES            1096
#define IDC_CHECK_HIDEPLSMLEFT          1097
#define IDC_SPIN_HIDEAFTER              1098
#define IDC_TEXTT_TITLEADDITIONAL       1099
#define IDC_TEXTT_TITLEPOSITION         1100
#define IDC_TEXTT_TITLECURRLANG         1101
#define IDC_TEXTT_TITLESEEKING          1102
#define IDC_TEXTT_REWINDBY              1103
#define IDC_TEXTT2_REWINDBY             1104
#define IDC_CHECK_FASTSEEK              1105
#define IDC_TEXTT_FASTSEEK              1106
#define IDC_TEXTT_TITLEASSOCIATED       1107
#define IDC_BUTTON_NONE                 1108
#define IDC_CHECK_REGISTERONSTART       1109
#define IDC_TEXTT_REGISTERONSTART       1110
#define IDC_TEXTT_TITLEOFFSET           1111
#define IDC_TEXTT_TIME                  1112
#define IDC_TEXTT2_TIME                 1113
#define IDC_STATIC_ICON                 1114
#define IDC_SLIDER_ICON                 1115
#define IDC_TEXTT_TITLEICON             1116
#define IDC_TEXTT_TRANSLATION           1117
#define IDC_TEXTT_TITLESKINIFNO         1118
#define IDC_TEXTT_TITLEPICTURE          1119
#define IDC_TEXTT_WINXPONLY             1120
#define IDC_TEXTT_BRIGHTNESS            1121
#define IDC_TEXTT_CONTRAST              1122
#define IDC_TEXTT_SATURATION            1123
#define IDC_TEXTT_TITLESFILTERS         1124
#define IDC_CAPTION                     1125
#define IDM_OPENMOVIE                   32777
#define IDM_OPENSUBTITLES               32780
#define IDM_PLAYPAUSE                   32781
#define IDM_REWINDBACK                  32782
#define IDM_REWINDFORWARD               32783
#define IDM_PREVMOVIE                   32784
#define IDM_NEXTMOVIE                   32785
#define IDM_OPTIONS                     32786
#define IDM_PLAYLIST                    32787
#define IDM_SKINBROWSER                 32788
#define IDM_FULLSCREEN                  32789
#define IDM_PANSCAN                     32790
#define IDM_SHOWSUBTITLES               32792
#define IDM_EXIT                        32793
#define IDM_STOP                        32795
#define IDM_PS_AUTO                     32796
#define IDM_PS_WIDE                     32797
#define IDM_PS_ZOOM10                   32799
#define IDM_PS_ZOOM30                   32800
#define IDM_PS_ZOOM20                   32801
#define IDM_PS_ZOOM25                   32802
#define IDM_PS_ZOOM35                   32803
#define IDM_PS_ZOOM50                   32804
#define IDM_PS_ZOOM40                   32805
#define IDM_FILTERSPROP                 32807
#define ID_QMPLS_CLEARPLS               32808
#define ID_QMPLS_ADDFILES               32809
#define ID_QMPLS_REMOVEFILE             32810
#define ID_QMPLS_CLOSE                  32811
#define IDM_CALLBACK_OPENFROMPLS        32813
#define IDM_CALLBACK_CLOSEDPLS          32814
#define IDM_CALLBACK_SKINCHANGED        32815
#define IDM_CALLBACK_FONTCHANGED        32816
#define IDM_CALLBACK_ALWAYSONTOPCHANGED 32817
#define IDM_CALLBACK_TRIEDLOADSUBTITLES 32818
#define IDM_CALLBACK_OFFSETSUBTITLESCHANGED 32819
#define IDM_CALLBACK_SUBTITLESPOSCHANGED 32820
#define IDM_CALLBACK_SAVESUBTITLES      32821
#define ID_QMPLS_OPEN                   32822
#define ID_QMPLS_SAVE                   32823
#define IDM_CALLBACK_LANGUAGECHANGED    32824
#define IDM_CALLBACK_OPENFROMMUTEX      32827

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32828
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
